import { $t } from 'services/i18n';
import { TStreamErrorType } from 'services/streaming/stream-error';

/**
 * Display YouTube API Error Details in a readable format
 * @remark Any changes to the error details in the YouTube API will not automatically update this list.
 * In that case, `formatErrorDetails` will format the error details separated by camel case. Not
 * ideal but better than showing nothing at all.
 */
export const reasonLabels: Record<string, string> = {
  accountDelegationForbidden: $t('Account Delegation Forbidden'),
  authenticatedUserAccountClosed: $t('Authenticated User Account Closed'),
  authenticatedUserAccountSuspended: $t('Authenticated User Account Suspended'),
  authenticatedUserNotChannel: $t('Authenticated User Not Channel'),
  authorizationRequired: $t('Authorization Required'),
  backendError: $t('Backend Error'),
  broadcastStreamDelayMsRequired: $t('Broadcast Stream Delay (ms) Required'),
  categoryNotFound: $t('Category Not Found'),
  cdnRequired: $t('CDN Required'),
  channelClosed: $t('Channel Closed'),
  channelForbidden: $t('Channel Forbidden'),
  channelNotFound: $t('Channel Not Found'),
  channelSuspended: $t('Channel Suspended'),
  closedCaptionsTypeModificationNotAllowed: $t('Closed Captions Type Modification Not Allowed'),
  cmsUserAccountNotFound: $t('CMS User Account Not Found'),
  concurrentBroadcastsExceedLimit: $t('Concurrent Broadcasts Exceed Limit'),
  contentOwnerAccountNotFound: $t('Content Owner Account Not Found'),
  defaultLanguageNotSet: $t('Default Language Not Set'),
  enableAutoStartModificationNotAllowed: $t('Enable Auto Start Modification Not Allowed'),
  enableClosedCaptionsModificationNotAllowed: $t('Enable Closed Captions Modification Not Allowed'),
  enableDvrModificationNotAllowed: $t('Enable DVR Modification Not Allowed'),
  enableMonitorStreamModificationNotAllowed: $t('Enable Monitor Stream Modification Not Allowed'),
  enableMonitorStreamRequired: $t('Enable Monitor Stream Required'),
  errorExecutingTransition: $t('Error Executing Transition'),
  errorStreamInactive: $t('Error Stream Inactive'),
  forbidden: $t('Forbidden'),
  forbiddenEmbedSetting: $t('Forbidden Embed Setting'),
  forbiddenLicenseSetting: $t('Forbidden License Setting'),
  forbiddenPrivacySetting: $t('Forbidden Privacy Setting'),
  frameRateRequired: $t('Frame Rate Required'),
  idRequired: $t('ID Required'),
  incompatibleParameters: $t('Incompatible Parameters'),
  ingestionTypeRequired: $t('Ingestion Type Required'),
  insufficientCapabilities: $t('Insufficient Capabilities'),
  insufficientLivePermissions: $t('Insufficient Live Permissions'),
  insufficientPermissions: $t('Insufficient Permissions'),
  internalError: $t('Internal Error'),
  invalidAutoStart: $t('Invalid Auto Start'),
  invalidAutoStop: $t('Invalid Auto Stop'),
  invalidCategoryId: $t('Invalid Category ID'),
  invalidCreatorCuepointConfig: $t('Invalid Creator Cuepoint Config'),
  invalidCriteria: $t('Invalid Criteria'),
  invalidCuepointSchedule: $t('Invalid Cuepoint Schedule'),
  invalidDefaultBroadcastPrivacySetting: $t('Invalid Default Broadcast Privacy Setting'),
  invalidDescription: $t('Invalid Description'),
  invalidEligibleForAdsMonetization: $t('Invalid Eligible For Ads Monetization'),
  invalidEmbedSetting: $t('Invalid Embed Setting'),
  invalidEnableClosedCaptions: $t('Invalid Enable Closed Captions'),
  invalidEnabled: $t('Invalid Enabled'),
  invalidFilename: $t('Invalid Filename'),
  invalidFilters: $t('Invalid Filters'),
  invalidFormat: $t('Invalid Format'),
  invalidFrameRate: $t('Invalid Frame Rate'),
  invalidImage: $t('Invalid Image'),
  invalidIngestionType: $t('Invalid Ingestion Type'),
  invalidLanguage: $t('Invalid Language'),
  invalidLatencyPreferenceOptions: $t('Invalid Latency Preference Options'),
  invalidMine: $t('Invalid Mine'),
  invalidPageToken: $t('Invalid Page Token'),
  invalidPart: $t('Invalid Part'),
  invalidPauseAdsUntil: $t('Invalid Pause Ads Until'),
  invalidPrivacyStatus: $t('Invalid Privacy Status'),
  invalidProjection: $t('Invalid Projection'),
  invalidPublishAt: $t('Invalid Publish At'),
  invalidRecordingDetails: $t('Invalid Recording Details'),
  invalidRegionCode: $t('Invalid Region Code'),
  invalidRepeatIntervalSecs: $t('Invalid Repeat Interval (secs)'),
  invalidResolution: $t('Invalid Resolution'),
  invalidScheduledEndTime: $t('Invalid Scheduled End Time'),
  invalidScheduledStartTime: $t('Invalid Scheduled Start Time'),
  invalidTags: $t('Invalid Tags'),
  invalidTitle: $t('Invalid Title'),
  invalidTransition: $t('Invalid Transition'),
  invalidVideoGameRating: $t('Invalid Video Game Rating'),
  invalidVideoMetadata: $t('Invalid Video Metadata'),
  liveBroadcastBindingNotAllowed: $t('Live Broadcast Binding Not Allowed'),
  liveBroadcastDeletionNotAllowed: $t('Live Broadcast Deletion Not Allowed'),
  liveBroadcastNotFound: $t('Live Broadcast Not Found'),
  livePermissionBlocked: $t('Live Permission Blocked'),
  liveStreamNotFound: $t('Live Stream Not Found'),
  liveStreamingNotEnabled: $t('Live Streaming Not Enabled'),
  mediaBodyRequired: $t('Media Body Required'),
  missingAdsMonetizationStatus: $t('Missing Ads Monetization Status'),
  missingRequiredParameter: $t('Missing Required Parameter'),
  monetizationDetailsModificationNotAllowed: $t('Monetization Details Modification Not Allowed'),
  pauseAdsUntilModificationNotAllowed: $t('Pause Ads Until Modification Not Allowed'),
  privacyStatusRequired: $t('Privacy Status Required'),
  quotaExceeded: $t('Quota Exceeded'),
  recordFromStartModificationNotAllowed: $t('Record From Start Modification Not Allowed'),
  redundantTransition: $t('Redundant Transition'),
  resolutionRequired: $t('Resolution Required'),
  scheduledEndTimeRequired: $t('Scheduled End Time Required'),
  scheduledStartTimeRequired: $t('Scheduled Start Time Required'),
  sharedIngestionBroadcastsExceedLimit: $t('Shared Ingestion Broadcasts Exceed Limit'),
  statusRequired: $t('Status Required'),
  titleRequired: $t('Title Required'),
  unexpectedParameter: $t('Unexpected Parameter'),
  unexpectedPart: $t('Unexpected Part'),
  unknownPart: $t('Unknown Part'),
  unsupportedLanguageCode: $t('Unsupported Language Code'),
  unsupportedRegionCode: $t('Unsupported Region Code'),
  uploadLimitExceeded: $t('Upload Limit Exceeded'),
  uploadRateLimitExceeded: $t('Upload Rate Limit Exceeded'),
  userBroadcastsExceedLimit: $t('User Broadcasts Exceed Limit'),
  userRequestsExceedRateLimit: $t('User Requests Exceed Rate Limit'),
  videoCategoryNotFound: $t('Video Category Not Found'),
  videoChartNotFound: $t('Video Chart Not Found'),
  videoNotEligibleForAdsMonetization: $t('Video Not Eligible For Ads Monetization'),
  videoNotFound: $t('Video Not Found'),
  youtubeSignupRequired: $t('YouTube Signup Required'),
};

/**
 * Map YouTube API endpoints to a corresponding `TStreamErrorType`
 * @remark Each endpoint has its own documented set of error reasons and its own `TStreamErrorType`,
 * so errors can be identified with the call that produced it instead of collapsed into `PLATFORM_REQUEST_FAILED`
 */
export const endpointErrorTypes: Record<string, TStreamErrorType> = {
  'liveBroadcasts/insert': 'YOUTUBE_CREATE_BROADCAST_FAILED',
  'liveBroadcasts/update': 'YOUTUBE_UPDATE_BROADCAST_FAILED',
  'liveBroadcasts/delete': 'YOUTUBE_DELETE_BROADCAST_FAILED',
  'liveBroadcasts/bind': 'YOUTUBE_BIND_STREAM_FAILED',
  'liveBroadcasts/transition': 'YOUTUBE_TRANSITION_BROADCAST_FAILED',
  'liveBroadcasts/list': 'YOUTUBE_FETCH_BROADCASTS_FAILED',
  'liveStreams/insert': 'YOUTUBE_CREATE_STREAM_FAILED',
  'liveStreams/list': 'YOUTUBE_FETCH_STREAM_FAILED',
  'videos/insert': 'YOUTUBE_UPLOAD_VIDEO_FAILED',
  'videos/update': 'YOUTUBE_UPDATE_VIDEO_FAILED',
  'videos/list': 'YOUTUBE_FETCH_VIDEO_FAILED',
  'videoCategories/list': 'YOUTUBE_FETCH_CATEGORIES_FAILED',
  'channels/list': 'YOUTUBE_FETCH_CHANNEL_FAILED',
  'thumbnails/set': 'YOUTUBE_THUMBNAIL_UPLOAD_FAILED',
};
