import { $t } from 'services/i18n';
import { TStreamErrorType } from 'services/streaming/stream-error';

export enum EYoutubeErrorReason {
  AccountDelegationForbidden = 'accountDelegationForbidden',
  AuthenticatedUserAccountClosed = 'authenticatedUserAccountClosed',
  AuthenticatedUserAccountSuspended = 'authenticatedUserAccountSuspended',
  AuthenticatedUserNotChannel = 'authenticatedUserNotChannel',
  AuthorizationRequired = 'authorizationRequired',
  BackendError = 'backendError',
  BroadcastStreamDelayMsRequired = 'broadcastStreamDelayMsRequired',
  CategoryNotFound = 'categoryNotFound',
  CdnRequired = 'cdnRequired',
  ChannelClosed = 'channelClosed',
  ChannelForbidden = 'channelForbidden',
  ChannelNotFound = 'channelNotFound',
  ChannelSuspended = 'channelSuspended',
  ClosedCaptionsTypeModificationNotAllowed = 'closedCaptionsTypeModificationNotAllowed',
  CmsUserAccountNotFound = 'cmsUserAccountNotFound',
  ConcurrentBroadcastsExceedLimit = 'concurrentBroadcastsExceedLimit',
  ContentOwnerAccountNotFound = 'contentOwnerAccountNotFound',
  DefaultLanguageNotSet = 'defaultLanguageNotSet',
  EnableAutoStartModificationNotAllowed = 'enableAutoStartModificationNotAllowed',
  EnableClosedCaptionsModificationNotAllowed = 'enableClosedCaptionsModificationNotAllowed',
  EnableDvrModificationNotAllowed = 'enableDvrModificationNotAllowed',
  EnableMonitorStreamModificationNotAllowed = 'enableMonitorStreamModificationNotAllowed',
  EnableMonitorStreamRequired = 'enableMonitorStreamRequired',
  ErrorExecutingTransition = 'errorExecutingTransition',
  ErrorStreamInactive = 'errorStreamInactive',
  Forbidden = 'forbidden',
  ForbiddenEmbedSetting = 'forbiddenEmbedSetting',
  ForbiddenLicenseSetting = 'forbiddenLicenseSetting',
  ForbiddenPrivacySetting = 'forbiddenPrivacySetting',
  FrameRateRequired = 'frameRateRequired',
  IdRequired = 'idRequired',
  IncompatibleParameters = 'incompatibleParameters',
  IngestionTypeRequired = 'ingestionTypeRequired',
  InsufficientCapabilities = 'insufficientCapabilities',
  InsufficientLivePermissions = 'insufficientLivePermissions',
  InsufficientPermissions = 'insufficientPermissions',
  InternalError = 'internalError',
  InvalidAutoStart = 'invalidAutoStart',
  InvalidAutoStop = 'invalidAutoStop',
  InvalidCategoryId = 'invalidCategoryId',
  InvalidCreatorCuepointConfig = 'invalidCreatorCuepointConfig',
  InvalidCriteria = 'invalidCriteria',
  InvalidCuepointSchedule = 'invalidCuepointSchedule',
  InvalidDefaultBroadcastPrivacySetting = 'invalidDefaultBroadcastPrivacySetting',
  InvalidDescription = 'invalidDescription',
  InvalidEligibleForAdsMonetization = 'invalidEligibleForAdsMonetization',
  InvalidEmbedSetting = 'invalidEmbedSetting',
  InvalidEnableClosedCaptions = 'invalidEnableClosedCaptions',
  InvalidEnabled = 'invalidEnabled',
  InvalidFilename = 'invalidFilename',
  InvalidFilters = 'invalidFilters',
  InvalidFormat = 'invalidFormat',
  InvalidFrameRate = 'invalidFrameRate',
  InvalidImage = 'invalidImage',
  InvalidIngestionType = 'invalidIngestionType',
  InvalidLanguage = 'invalidLanguage',
  InvalidLatencyPreferenceOptions = 'invalidLatencyPreferenceOptions',
  InvalidMine = 'invalidMine',
  InvalidPageToken = 'invalidPageToken',
  InvalidPart = 'invalidPart',
  InvalidPauseAdsUntil = 'invalidPauseAdsUntil',
  InvalidPrivacyStatus = 'invalidPrivacyStatus',
  InvalidProjection = 'invalidProjection',
  InvalidPublishAt = 'invalidPublishAt',
  InvalidRecordingDetails = 'invalidRecordingDetails',
  InvalidRegionCode = 'invalidRegionCode',
  InvalidRepeatIntervalSecs = 'invalidRepeatIntervalSecs',
  InvalidResolution = 'invalidResolution',
  InvalidScheduledEndTime = 'invalidScheduledEndTime',
  InvalidScheduledStartTime = 'invalidScheduledStartTime',
  InvalidTags = 'invalidTags',
  InvalidTitle = 'invalidTitle',
  InvalidTransition = 'invalidTransition',
  InvalidVideoGameRating = 'invalidVideoGameRating',
  InvalidVideoMetadata = 'invalidVideoMetadata',
  LiveBroadcastBindingNotAllowed = 'liveBroadcastBindingNotAllowed',
  LiveBroadcastDeletionNotAllowed = 'liveBroadcastDeletionNotAllowed',
  LiveBroadcastNotFound = 'liveBroadcastNotFound',
  LivePermissionBlocked = 'livePermissionBlocked',
  LiveStreamNotFound = 'liveStreamNotFound',
  LiveStreamingNotEnabled = 'liveStreamingNotEnabled',
  MediaBodyRequired = 'mediaBodyRequired',
  MissingAdsMonetizationStatus = 'missingAdsMonetizationStatus',
  MissingRequiredParameter = 'missingRequiredParameter',
  MonetizationDetailsModificationNotAllowed = 'monetizationDetailsModificationNotAllowed',
  PauseAdsUntilModificationNotAllowed = 'pauseAdsUntilModificationNotAllowed',
  PrivacyStatusRequired = 'privacyStatusRequired',
  QuotaExceeded = 'quotaExceeded',
  RecordFromStartModificationNotAllowed = 'recordFromStartModificationNotAllowed',
  RedundantTransition = 'redundantTransition',
  ResolutionRequired = 'resolutionRequired',
  ScheduledEndTimeRequired = 'scheduledEndTimeRequired',
  ScheduledStartTimeRequired = 'scheduledStartTimeRequired',
  SharedIngestionBroadcastsExceedLimit = 'sharedIngestionBroadcastsExceedLimit',
  StatusRequired = 'statusRequired',
  TitleRequired = 'titleRequired',
  UnexpectedParameter = 'unexpectedParameter',
  UnexpectedPart = 'unexpectedPart',
  UnknownPart = 'unknownPart',
  UnsupportedLanguageCode = 'unsupportedLanguageCode',
  UnsupportedRegionCode = 'unsupportedRegionCode',
  UploadLimitExceeded = 'uploadLimitExceeded',
  UploadRateLimitExceeded = 'uploadRateLimitExceeded',
  UserBroadcastsExceedLimit = 'userBroadcastsExceedLimit',
  UserRequestsExceedRateLimit = 'userRequestsExceedRateLimit',
  VideoCategoryNotFound = 'videoCategoryNotFound',
  VideoChartNotFound = 'videoChartNotFound',
  VideoNotEligibleForAdsMonetization = 'videoNotEligibleForAdsMonetization',
  VideoNotFound = 'videoNotFound',
  YoutubeSignupRequired = 'youtubeSignupRequired',
}

export enum EYoutubeErrorEndpoint {
  LiveBroadcastInsert = 'liveBroadcasts/insert',
  LiveBroadcastUpdate = 'liveBroadcasts/update',
  LiveBroadcastDelete = 'liveBroadcasts/delete',
  LiveBroadcastBind = 'liveBroadcasts/bind',
  LiveBroadcastTransition = 'liveBroadcasts/transition',
  LiveBroadcastList = 'liveBroadcasts/list',
  LiveStreamsInsert = 'liveStreams/insert',
  LiveStreamsList = 'liveStreams/list',
  VideosInsert = 'videos/insert',
  VideosUpdate = 'videos/update',
  VideosList = 'videos/list',
  VideoCategoriesList = 'videoCategories/list',
  ChannelsList = 'channels/list',
  ThumbnailsSet = 'thumbnails/set',
}

/**
 * Display YouTube API Error Details in a readable format
 * @remark Any changes to the error details in the YouTube API will not automatically update this list.
 * In that case, `formatErrorDetails` will format the error details separated by camel case. Not
 * ideal but better than showing nothing at all.
 */
export const reasonLabels = (reason: EYoutubeErrorReason) =>
  ({
    [EYoutubeErrorReason.AccountDelegationForbidden]: $t('Account Delegation Forbidden'),
    [EYoutubeErrorReason.AuthenticatedUserAccountClosed]: $t('Authenticated User Account Closed'),
    [EYoutubeErrorReason.AuthenticatedUserAccountSuspended]: $t(
      'Authenticated User Account Suspended',
    ),
    [EYoutubeErrorReason.AuthenticatedUserNotChannel]: $t('Authenticated User Not Channel'),
    [EYoutubeErrorReason.AuthorizationRequired]: $t('Authorization Required'),
    [EYoutubeErrorReason.BackendError]: $t('Backend Error'),
    [EYoutubeErrorReason.BroadcastStreamDelayMsRequired]: $t(
      'Broadcast Stream Delay (ms) Required',
    ),
    [EYoutubeErrorReason.CategoryNotFound]: $t('Category Not Found'),
    [EYoutubeErrorReason.CdnRequired]: $t('CDN Required'),
    [EYoutubeErrorReason.ChannelClosed]: $t('Channel Closed'),
    [EYoutubeErrorReason.ChannelForbidden]: $t('Channel Forbidden'),
    [EYoutubeErrorReason.ChannelNotFound]: $t('Channel Not Found'),
    [EYoutubeErrorReason.ChannelSuspended]: $t('Channel Suspended'),
    [EYoutubeErrorReason.ClosedCaptionsTypeModificationNotAllowed]: $t(
      'Closed Captions Type Modification Not Allowed',
    ),
    [EYoutubeErrorReason.CmsUserAccountNotFound]: $t('CMS User Account Not Found'),
    [EYoutubeErrorReason.ConcurrentBroadcastsExceedLimit]: $t('Concurrent Broadcasts Exceed Limit'),
    [EYoutubeErrorReason.ContentOwnerAccountNotFound]: $t('Content Owner Account Not Found'),
    [EYoutubeErrorReason.DefaultLanguageNotSet]: $t('Default Language Not Set'),
    [EYoutubeErrorReason.EnableAutoStartModificationNotAllowed]: $t(
      'Enable Auto Start Modification Not Allowed',
    ),
    [EYoutubeErrorReason.EnableClosedCaptionsModificationNotAllowed]: $t(
      'Enable Closed Captions Modification Not Allowed',
    ),
    [EYoutubeErrorReason.EnableDvrModificationNotAllowed]: $t(
      'Enable DVR Modification Not Allowed',
    ),
    [EYoutubeErrorReason.EnableMonitorStreamModificationNotAllowed]: $t(
      'Enable Monitor Stream Modification Not Allowed',
    ),
    [EYoutubeErrorReason.EnableMonitorStreamRequired]: $t('Enable Monitor Stream Required'),
    [EYoutubeErrorReason.ErrorExecutingTransition]: $t('Error Executing Transition'),
    [EYoutubeErrorReason.ErrorStreamInactive]: $t('Error Stream Inactive'),
    [EYoutubeErrorReason.Forbidden]: $t('Forbidden'),
    [EYoutubeErrorReason.ForbiddenEmbedSetting]: $t('Forbidden Embed Setting'),
    [EYoutubeErrorReason.ForbiddenLicenseSetting]: $t('Forbidden License Setting'),
    [EYoutubeErrorReason.ForbiddenPrivacySetting]: $t('Forbidden Privacy Setting'),
    [EYoutubeErrorReason.FrameRateRequired]: $t('Frame Rate Required'),
    [EYoutubeErrorReason.IdRequired]: $t('ID Required'),
    [EYoutubeErrorReason.IncompatibleParameters]: $t('Incompatible Parameters'),
    [EYoutubeErrorReason.IngestionTypeRequired]: $t('Ingestion Type Required'),
    [EYoutubeErrorReason.InsufficientCapabilities]: $t('Insufficient Capabilities'),
    [EYoutubeErrorReason.InsufficientLivePermissions]: $t('Insufficient Live Permissions'),
    [EYoutubeErrorReason.InsufficientPermissions]: $t('Insufficient Permissions'),
    [EYoutubeErrorReason.InternalError]: $t('Internal Error'),
    [EYoutubeErrorReason.InvalidAutoStart]: $t('Invalid Auto Start'),
    [EYoutubeErrorReason.InvalidAutoStop]: $t('Invalid Auto Stop'),
    [EYoutubeErrorReason.InvalidCategoryId]: $t('Invalid Category ID'),
    [EYoutubeErrorReason.InvalidCreatorCuepointConfig]: $t('Invalid Creator Cuepoint Config'),
    [EYoutubeErrorReason.InvalidCriteria]: $t('Invalid Criteria'),
    [EYoutubeErrorReason.InvalidCuepointSchedule]: $t('Invalid Cuepoint Schedule'),
    [EYoutubeErrorReason.InvalidDefaultBroadcastPrivacySetting]: $t(
      'Invalid Default Broadcast Privacy Setting',
    ),
    [EYoutubeErrorReason.InvalidDescription]: $t('Invalid Description'),
    [EYoutubeErrorReason.InvalidEligibleForAdsMonetization]: $t(
      'Invalid Eligible For Ads Monetization',
    ),
    [EYoutubeErrorReason.InvalidEmbedSetting]: $t('Invalid Embed Setting'),
    [EYoutubeErrorReason.InvalidEnableClosedCaptions]: $t('Invalid Enable Closed Captions'),
    [EYoutubeErrorReason.InvalidEnabled]: $t('Invalid Enabled'),
    [EYoutubeErrorReason.InvalidFilename]: $t('Invalid Filename'),
    [EYoutubeErrorReason.InvalidFilters]: $t('Invalid Filters'),
    [EYoutubeErrorReason.InvalidFormat]: $t('Invalid Format'),
    [EYoutubeErrorReason.InvalidFrameRate]: $t('Invalid Frame Rate'),
    [EYoutubeErrorReason.InvalidImage]: $t('Invalid Image'),
    [EYoutubeErrorReason.InvalidIngestionType]: $t('Invalid Ingestion Type'),
    [EYoutubeErrorReason.InvalidLanguage]: $t('Invalid Language'),
    [EYoutubeErrorReason.InvalidLatencyPreferenceOptions]: $t('Invalid Latency Preference Options'),
    [EYoutubeErrorReason.InvalidMine]: $t('Invalid Mine'),
    [EYoutubeErrorReason.InvalidPageToken]: $t('Invalid Page Token'),
    [EYoutubeErrorReason.InvalidPart]: $t('Invalid Part'),
    [EYoutubeErrorReason.InvalidPauseAdsUntil]: $t('Invalid Pause Ads Until'),
    [EYoutubeErrorReason.InvalidPrivacyStatus]: $t('Invalid Privacy Status'),
    [EYoutubeErrorReason.InvalidProjection]: $t('Invalid Projection'),
    [EYoutubeErrorReason.InvalidPublishAt]: $t('Invalid Publish At'),
    [EYoutubeErrorReason.InvalidRecordingDetails]: $t('Invalid Recording Details'),
    [EYoutubeErrorReason.InvalidRegionCode]: $t('Invalid Region Code'),
    [EYoutubeErrorReason.InvalidRepeatIntervalSecs]: $t('Invalid Repeat Interval (secs)'),
    [EYoutubeErrorReason.InvalidResolution]: $t('Invalid Resolution'),
    [EYoutubeErrorReason.InvalidScheduledEndTime]: $t('Invalid Scheduled End Time'),
    [EYoutubeErrorReason.InvalidScheduledStartTime]: $t('Invalid Scheduled Start Time'),
    [EYoutubeErrorReason.InvalidTags]: $t('Invalid Tags'),
    [EYoutubeErrorReason.InvalidTitle]: $t('Invalid Title'),
    [EYoutubeErrorReason.InvalidTransition]: $t('Invalid Transition'),
    [EYoutubeErrorReason.InvalidVideoGameRating]: $t('Invalid Video Game Rating'),
    [EYoutubeErrorReason.InvalidVideoMetadata]: $t('Invalid Video Metadata'),
    [EYoutubeErrorReason.LiveBroadcastBindingNotAllowed]: $t('Live Broadcast Binding Not Allowed'),
    [EYoutubeErrorReason.LiveBroadcastDeletionNotAllowed]: $t(
      'Live Broadcast Deletion Not Allowed',
    ),
    [EYoutubeErrorReason.LiveBroadcastNotFound]: $t('Live Broadcast Not Found'),
    [EYoutubeErrorReason.LivePermissionBlocked]: $t('Live Permission Blocked'),
    [EYoutubeErrorReason.LiveStreamNotFound]: $t('Live Stream Not Found'),
    [EYoutubeErrorReason.LiveStreamingNotEnabled]: $t('Live Streaming Not Enabled'),
    [EYoutubeErrorReason.MediaBodyRequired]: $t('Media Body Required'),
    [EYoutubeErrorReason.MissingAdsMonetizationStatus]: $t('Missing Ads Monetization Status'),
    [EYoutubeErrorReason.MissingRequiredParameter]: $t('Missing Required Parameter'),
    [EYoutubeErrorReason.MonetizationDetailsModificationNotAllowed]: $t(
      'Monetization Details Modification Not Allowed',
    ),
    [EYoutubeErrorReason.PauseAdsUntilModificationNotAllowed]: $t(
      'Pause Ads Until Modification Not Allowed',
    ),
    [EYoutubeErrorReason.PrivacyStatusRequired]: $t('Privacy Status Required'),
    [EYoutubeErrorReason.QuotaExceeded]: $t('Quota Exceeded'),
    [EYoutubeErrorReason.RecordFromStartModificationNotAllowed]: $t(
      'Record From Start Modification Not Allowed',
    ),
    [EYoutubeErrorReason.RedundantTransition]: $t('Redundant Transition'),
    [EYoutubeErrorReason.ResolutionRequired]: $t('Resolution Required'),
    [EYoutubeErrorReason.ScheduledEndTimeRequired]: $t('Scheduled End Time Required'),
    [EYoutubeErrorReason.ScheduledStartTimeRequired]: $t('Scheduled Start Time Required'),
    [EYoutubeErrorReason.SharedIngestionBroadcastsExceedLimit]: $t(
      'Shared Ingestion Broadcasts Exceed Limit',
    ),
    [EYoutubeErrorReason.StatusRequired]: $t('Status Required'),
    [EYoutubeErrorReason.TitleRequired]: $t('Title Required'),
    [EYoutubeErrorReason.UnexpectedParameter]: $t('Unexpected Parameter'),
    [EYoutubeErrorReason.UnexpectedPart]: $t('Unexpected Part'),
    [EYoutubeErrorReason.UnknownPart]: $t('Unknown Part'),
    [EYoutubeErrorReason.UnsupportedLanguageCode]: $t('Unsupported Language Code'),
    [EYoutubeErrorReason.UnsupportedRegionCode]: $t('Unsupported Region Code'),
    [EYoutubeErrorReason.UploadLimitExceeded]: $t('Upload Limit Exceeded'),
    [EYoutubeErrorReason.UploadRateLimitExceeded]: $t('Upload Rate Limit Exceeded'),
    [EYoutubeErrorReason.UserBroadcastsExceedLimit]: $t('User Broadcasts Exceed Limit'),
    [EYoutubeErrorReason.UserRequestsExceedRateLimit]: $t('User Requests Exceed Rate Limit'),
    [EYoutubeErrorReason.VideoCategoryNotFound]: $t('Video Category Not Found'),
    [EYoutubeErrorReason.VideoChartNotFound]: $t('Video Chart Not Found'),
    [EYoutubeErrorReason.VideoNotEligibleForAdsMonetization]: $t(
      'Video Not Eligible For Ads Monetization',
    ),
    [EYoutubeErrorReason.VideoNotFound]: $t('Video Not Found'),
    [EYoutubeErrorReason.YoutubeSignupRequired]: $t('YouTube Signup Required'),
  }[reason]);

/**
 * Map YouTube API endpoints to a corresponding `TStreamErrorType`
 * @remark Each endpoint has its own documented set of error reasons and its own `TStreamErrorType`,
 * so errors can be identified with the call that produced it instead of collapsed into `PLATFORM_REQUEST_FAILED`
 */
export const endpointErrorTypes: Record<string, TStreamErrorType> = {
  [EYoutubeErrorEndpoint.LiveBroadcastInsert]: 'YOUTUBE_CREATE_BROADCAST_FAILED',
  [EYoutubeErrorEndpoint.LiveBroadcastUpdate]: 'YOUTUBE_UPDATE_BROADCAST_FAILED',
  [EYoutubeErrorEndpoint.LiveBroadcastDelete]: 'YOUTUBE_DELETE_BROADCAST_FAILED',
  [EYoutubeErrorEndpoint.LiveBroadcastBind]: 'YOUTUBE_BIND_STREAM_FAILED',
  [EYoutubeErrorEndpoint.LiveBroadcastTransition]: 'YOUTUBE_TRANSITION_BROADCAST_FAILED',
  [EYoutubeErrorEndpoint.LiveBroadcastList]: 'YOUTUBE_FETCH_BROADCASTS_FAILED',
  [EYoutubeErrorEndpoint.LiveStreamsInsert]: 'YOUTUBE_CREATE_STREAM_FAILED',
  [EYoutubeErrorEndpoint.LiveStreamsList]: 'YOUTUBE_FETCH_STREAM_FAILED',
  [EYoutubeErrorEndpoint.VideosInsert]: 'YOUTUBE_UPLOAD_VIDEO_FAILED',
  [EYoutubeErrorEndpoint.VideosUpdate]: 'YOUTUBE_UPDATE_VIDEO_FAILED',
  [EYoutubeErrorEndpoint.VideosList]: 'YOUTUBE_FETCH_VIDEO_FAILED',
  [EYoutubeErrorEndpoint.VideoCategoriesList]: 'YOUTUBE_FETCH_CATEGORIES_FAILED',
  [EYoutubeErrorEndpoint.ChannelsList]: 'YOUTUBE_FETCH_CHANNEL_FAILED',
  [EYoutubeErrorEndpoint.ThumbnailsSet]: 'YOUTUBE_THUMBNAIL_UPLOAD_FAILED',
};

export interface IYouTubeErrorResponse {
  result: {
    error: {
      code: number;
      errors: IYouTubeError[];
      message: string;
    };
  };
}

export interface IYouTubeError {
  message: string;
  domain: string;
  location: string;
  locationType: string;
  reason: EYoutubeErrorReason;
}
